### ISSUE TITLE
Update bcrypt-ruby to bcrypt

### ISSUE THREAD

**Issue by thagomizer** [seattlerb/seattlerb.org#101]
Our version of devise is outdated and is causing an error. See
https://github.com/plataformatec/devise/issues/2901

**Comment by jakegavin** [comment]
Looks like @tlynam took care of this in the Rails 4.2 upgrade. It's on the latest version of Devise, [3.4.1](https://rubygems.org/gems/devise/versions/3.4.1), which uses bcrypt.
https://github.com/seattlerb/seattlerb.org/pull/112/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R12

**Comment by zenspider** [comment]
Closing
