### ISSUE TITLE
Join Us page: The sayat widget seems defunct

### ISSUE THREAD

**Issue by olleolleolle** [seattlerb/seattlerb.org#152]
I'm browsing the pages, and found that the SayAt widget seems out of service. Maybe it can be removed?

https://github.com/seattlerb/seattlerb.org/search?q=feedback_iframe&unscoped_q=feedback_iframe

**Comment by olleolleolle** [comment]
(Also, 👋 here's a friendly wave from sunny Malmö in Sweden, host to Malmö.rb.)

**Comment by zenspider** [comment]
For whatever reason, the widget thing no longer exists. No instructions on how to update. I made it a plain link for now. Thanks for the heads up!
