### ISSUE TITLE
Changed github username, can't reset password

### ISSUE THREAD

**Issue by dreadwail** [seattlerb/seattlerb.org#155]
I recently changed my github username from `benlakey` to `dreadwail`.  I also don't recall my password for seattlerb.org.   So I used the forgot-password feature to try and reset my password but there seems to be a bug because it refuses to save my new password because it can't process the old github username. Screenshot attached:

![seattlerbfail](https://user-images.githubusercontent.com/712322/62839324-7d234080-bc3d-11e9-9022-2dedbe75eab7.PNG)

**Comment by dreadwail** [comment]
FYI I worked around this in the meantime by creating a `benlakey` github account and then re-doing the seattlerb forgot-password dance.  So this issue is just for the bug.  I'd submit a PR to address it but I'm not sure what the desired functionality is: (should it legitimately fail like this when the old github name doesnt exist? Or should it permit existing accounts to re-save even if the github account does not exist?)

**Comment by zenspider** [comment]
Damn good question. Looking at your data everything looks peachy now, including the new twitter/github name. Unfortunately those logs and the debugging info is looong gone. Looking at the code, and trying it out manually, your new username works fine via the github api... but I wonder if at the time it was set up as a redirect or was cached or something.

**Comment by zenspider** [comment]
And yeah... PRs welcome, but no clue what you're gonna do about this one. :P

**Comment by zenspider** [comment]
Things seem ok? Close?
