### ISSUE TITLE
Setup an exception tracker

### ISSUE THREAD

**Issue by phiggins** [seattlerb/seattlerb.org#82]
Having an exception tracker email us when something was broken on the site would have given us a heads up about #80, for example. There are a bunch with free plans on heroku, honeybadger is the one I've had the most recent exposure to:

https://addons.heroku.com/honeybadger

**Comment by zenspider** [comment]
I'm not paying $12/mo for this website... are you?

**Comment by zenspider** [comment]
I just provisioned airbrake... dunno what that means at this point, but I did it. Closing.
