### ISSUE TITLE
Members w/o image_url value cause 500

### ISSUE THREAD

**Issue by zenspider** [seattlerb/seattlerb.org#92]
It either needs to gracefully not have an image or, better(?), update the image.

**Comment by TLynam** [comment]
Hi @zenspider, @phiggins found this free Heroku Scheduler addon that can run the update_avatars rake task daily https://devcenter.heroku.com/articles/scheduler

**Comment by zenspider** [comment]
> On Mar 17, 2015, at 21:05, Todd Lynam <notifications@github.com> wrote:
> 
> Hi @zenspider, @phiggins found this free Heroku Scheduler addon that can run the update_avatars rake task daily https://devcenter.heroku.com/articles/scheduler

do it!

**Comment by zenspider** [comment]
I think this is handled...
